"""
serve.py
========
Entry point for kv_offload_lab.  Selects a KV offloading backend via
--kv-offloading-backend and translates it into vLLM's --kv-transfer-config.

Supported backends
------------------
  cpu     - vLLM's built-in CPUOffloadingSpec (CPU RAM, CUDA only)
  labcpu  - LabCPUOffloadingSpec: editable copy of vLLM's CPU backend
  nvme    - NVMeOffloadingSpec: file-based NVMe offloading (CUDA + Metal)

Usage
-----
  # Linux / CUDA
  python serve.py \\
      --model meta-llama/Llama-3.2-3B-Instruct \\
      --kv-offloading-backend labcpu \\
      --kv-offloading-size 16

  # Mac / Metal
  source ~/.venv-vllm-metal/bin/activate
  python serve.py \\
      --model mlx-community/Llama-3.2-3B-Instruct-4bit \\
      --kv-offloading-backend nvme \\
      --kv-offloading-size 10
"""

import json
import os
import site
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

_PTH_NAME  = "metalworker_patch.pth"
_SHIM_NAME = "metalworker_patch.py"


def _is_metal() -> bool:
    import platform
    return platform.system() == "Darwin" and platform.machine() == "arm64"


def install_patch():
    """Install the MetalWorker patch via a .pth file into the active venv."""
    site_pkgs = site.getsitepackages()
    if not site_pkgs:
        print("ERROR: could not find site-packages directory.")
        sys.exit(1)
    site_dir = site_pkgs[0]

    src = os.path.join(HERE, "patch.py")
    if not os.path.exists(src):
        print(f"ERROR: patch.py not found at {src}")
        sys.exit(1)

    shim_dst = os.path.join(site_dir, _SHIM_NAME)
    shim_content = f"""\
# Auto-generated by serve.py — applies MetalWorker KV connector patch.
# Safe to delete; will be regenerated next time serve.py runs.
import importlib.util as _ilu, os as _os
_spec = _ilu.spec_from_file_location("_metalworker_patch_impl", {src!r})
if _spec:
    _mod = _ilu.module_from_spec(_spec)
    try:
        _spec.loader.exec_module(_mod)
    except Exception:
        pass
"""
    with open(shim_dst, "w") as f:
        f.write(shim_content)

    pth_dst = os.path.join(site_dir, _PTH_NAME)
    with open(pth_dst, "w") as f:
        f.write("import metalworker_patch\n")

    print(f"Installed MetalWorker patch via {pth_dst}")


def _gb_to_bytes(gb: float) -> int:
    return int(gb * 1024 ** 3)


def _gb_to_blocks(gb: float, bytes_per_block: int = 2 * 1024 * 1024) -> int:
    return int(_gb_to_bytes(gb) / bytes_per_block)


def main():
    import argparse

    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument(
        "--kv-offloading-backend",
        default=None,
        choices=["cpu", "labcpu", "labcpu_inline", "labcpu_tiered", "nvme"],
        help="KV offloading backend to use.",
    )
    pre.add_argument(
        "--kv-offloading-size",
        type=float,
        default=None,
        help="Storage budget in GB (RAM for cpu/labcpu, disk for nvme).",
    )
    pre.add_argument(
        "--kv-offloading-eviction-policy",
        default="lru",
        choices=["lru", "arc", "evolved"],
    )
    known, remaining = pre.parse_known_args(sys.argv[1:])

    backend = known.kv_offloading_backend
    size_gb = known.kv_offloading_size
    eviction = known.kv_offloading_eviction_policy

    if backend == "cpu":
        # Use vLLM's built-in CPUOffloadingSpec — no spec_module_path needed,
        # the factory resolves "CPUOffloadingSpec" by default.
        gb = size_gb or 4.0
        kv_cfg = json.dumps({
            "kv_connector": "OffloadingConnector",
            "kv_role": "kv_both",
            "kv_connector_extra_config": {
                "spec_name": "CPUOffloadingSpec",
                "cpu_bytes_to_use": _gb_to_bytes(gb),
                "eviction_policy": eviction,
            },
        })
        remaining += ["--kv-transfer-config", kv_cfg]

    elif backend == "labcpu":
        gb = size_gb or 4.0
        kv_cfg = json.dumps({
            "kv_connector": "OffloadingConnector",
            "kv_role": "kv_both",
            "kv_connector_extra_config": {
                "spec_name": "LabCPUOffloadingSpec",
                "spec_module_path": "kv_offload_lab.backends.labcpu.spec",
                "cpu_bytes_to_use": _gb_to_bytes(gb),
                "eviction_policy": eviction,
            },
        })
        remaining += ["--kv-transfer-config", kv_cfg]

    elif backend == "labcpu_inline":
        gb = size_gb or 4.0
        kv_cfg = json.dumps({
            "kv_connector": "OffloadingConnector",
            "kv_role": "kv_both",
            "kv_connector_extra_config": {
                "spec_name": "LabCPUInlineOffloadingSpec",
                "spec_module_path": "kv_offload_lab.backends.labcpu_inline.spec",
                "cpu_bytes_to_use": _gb_to_bytes(gb),
                "eviction_policy": eviction,
            },
        })
        remaining += ["--kv-transfer-config", kv_cfg]

    elif backend == "labcpu_tiered":
        gb = size_gb or 4.0
        kv_cfg = json.dumps({
            "kv_connector": "OffloadingConnector",
            "kv_role": "kv_both",
            "kv_connector_extra_config": {
                "spec_name": "LabCPUTieredOffloadingSpec",
                "spec_module_path": "kv_offload_lab.backends.labcpu_tiered.spec",
                "cpu_bytes_to_use": _gb_to_bytes(gb),
                "eviction_policy": eviction,
            },
        })
        remaining += ["--kv-transfer-config", kv_cfg]

    elif backend == "nvme":
        gb = size_gb or 10.0
        num_blocks = _gb_to_blocks(gb)
        kv_cfg = json.dumps({
            "kv_connector": "OffloadingConnector",
            "kv_role": "kv_both",
            "kv_connector_extra_config": {
                "spec_name": "NVMeOffloadingSpec",
                "spec_module_path": "kv_offload_lab.backends.nvme.spec",
                "num_cpu_blocks": num_blocks,
                "eviction_policy": eviction,
            },
        })
        remaining += ["--kv-transfer-config", kv_cfg]

    # Install MetalWorker patch on Apple Silicon
    if _is_metal():
        install_patch()
        os.environ.setdefault("VLLM_METAL_USE_PAGED_ATTENTION", "1")
        os.environ.setdefault(
            "VLLM_NVME_OFFLOAD_PATH",
            os.path.expanduser("~/ai-native-systems/VSCodeProjects/vllm-metal/kv_cache"),
        )
        os.environ.setdefault("VLLM_METAL_MEMORY_FRACTION", "0.45")

    from vllm.entrypoints.openai.api_server import run_server
    from vllm.utils.argparse_utils import FlexibleArgumentParser
    from vllm.entrypoints.openai.cli_args import make_arg_parser
    import asyncio

    parser = make_arg_parser(FlexibleArgumentParser(
        description="vllm serve (kv_offload_lab)"
    ))
    args = parser.parse_args(remaining)
    asyncio.run(run_server(args))


if __name__ == "__main__":
    main()
